// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Process$LidcoreBsNode = require("@lidcore/bs-node/src/process.js");

var handlers = { };

function on_info(fn) {
  handlers["info"] = fn;
  return /* () */0;
}

function on_error(fn) {
  handlers["error"] = fn;
  return /* () */0;
}

function info(s) {
  console.log(s);
  var match = handlers["info"];
  if (match !== undefined) {
    return Curry._1(match, s);
  } else {
    return /* () */0;
  }
}

var error_log = function (m){console.error(m);};

function error(s) {
  error_log(s);
  var match = handlers["error"];
  if (match !== undefined) {
    return Curry._1(match, s);
  } else {
    return /* () */0;
  }
}

Process$LidcoreBsNode.on(/* `UncaughtException */[
      791088858,
      (function (exn) {
          error(exn);
          throw exn;
        })
    ]);

exports.on_info = on_info;
exports.info = info;
exports.on_error = on_error;
exports.error = error;
/*  Not a pure module */
