// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

process.on("uncaughtException", (function (exn) {
        throw exn;
      }));

function info(s) {
  console.log(s);
  return /* () */0;
}

var error_log = (function (m) {
    console.error(m);
  });

function error(s) {
  return error_log(s);
}

function Make(funarg) {
  process.on("uncaughtException", (function (exn) {
          Curry._1(funarg[/* error */1], exn);
          throw exn;
        }));
  var info = function (s) {
    Curry._1(funarg[/* info */0], s);
    console.log(s);
    return /* () */0;
  };
  var error_log = (function (m) {
    console.error(m);
  });
  var error = function (s) {
    Curry._1(funarg[/* error */1], s);
    return error_log(s);
  };
  return [
          info,
          error
        ];
}

exports.Make = Make;
exports.info = info;
exports.error = error;
/*  Not a pure module */
