// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function now() {
  return Date.now();
}

function init(prim) {
  return new Date(prim);
}

function getFullYear(prim) {
  return prim.getFullYear();
}

function getDate(prim) {
  return prim.getDate();
}

function getMonth(prim) {
  return prim.getMonth();
}

exports.now = now;
exports.init = init;
exports.getFullYear = getFullYear;
exports.getDate = getDate;
exports.getMonth = getMonth;
/* No side effect */
