// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Dotenv = require("dotenv");

function config() {
  Dotenv.config();
  return /* () */0;
}

exports.config = config;
/* dotenv Not a pure module */
