// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Env$LidcoreDraco = require("../lib/env.js");
var Utils$LidcoreDraco = require("../lib/utils.js");
var Buffer$LidcoreBsNode = require("@lidcore/bs-node/src/buffer.js");

var loadFunctions = function (){require("firebase-functions")};

var initApp = function (){require("firebase-admin").initializeApp()};

var enabled = Env$LidcoreDraco.get(/* Some */["no"], "IS_FIREBASE") === "yes";

if (enabled) {
  loadFunctions();
  initApp();
}

var https = function (){return require("firebase-functions").https};

function from_express(app) {
  return https().onRequest(app);
}

var pubsub = function (){return require("firebase-functions").pubsub};

function on_publish(name, handler) {
  return pubsub().topic(name).onPublish(handler);
}

function json(message) {
  return Curry._1(Utils$LidcoreDraco.Json[/* parse */0], Buffer$LidcoreBsNode.toString(/* None */0, /* None */0, /* None */0, Buffer$LidcoreBsNode.from(/* Some */["base64"], message.data)));
}

var Functions_001 = [from_express];

var Functions_002 = [
  on_publish,
  json
];

var Functions = [
  enabled,
  Functions_001,
  Functions_002
];

exports.Functions = Functions;
/* enabled Not a pure module */
