// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var BsAsyncMonad = require("bs-async-monad/src/bsAsyncMonad.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Env$LidcoreDraco = require("../env.js");
var Date$LidcoreDraco = require("./date.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Utils$LidcoreDraco = require("../utils.js");
var Pubsub = require("@google-cloud/pubsub");
var Buffer$LidcoreBsNode = require("@lidcore/bs-node/src/buffer.js");
var Compute = require("@google-cloud/compute");
var Storage = require("@google-cloud/storage");
var Firestore = require("@google-cloud/firestore");

var project = Env$LidcoreDraco.get(/* Some */["komodo-dev"], "PROJECT");

var default_config = {
  projectId: project
};

function init($staropt$star, _) {
  return new Pubsub($staropt$star ? $staropt$star[0] : default_config);
}

function get_topic(pubsub, name) {
  var partial_arg = pubsub.topic(name);
  var partial_arg$1 = BsAsyncMonad.Callback[/* return */2];
  return (function (param) {
      return partial_arg$1(partial_arg, param);
    });
}

function subscription(config, topic, client, name) {
  return BsAsyncMonad.Callback[/* >> */5](get_topic(client, topic), (function (topic) {
                var subscription = topic.subscription(name, config);
                return BsAsyncMonad.Callback[/* >> */5]((function (param) {
                              subscription.exists(param);
                              return /* () */0;
                            }), (function (ret) {
                              var tmp;
                              if (ret) {
                                var partial_arg = BsAsyncMonad.Callback[/* return */2];
                                tmp = (function (param) {
                                    return partial_arg(/* () */0, param);
                                  });
                              } else {
                                tmp = (function (param) {
                                    subscription.create(param);
                                    return /* () */0;
                                  });
                              }
                              return BsAsyncMonad.Callback[/* >> */5](tmp, (function () {
                                            var partial_arg = BsAsyncMonad.Callback[/* return */2];
                                            return (function (param) {
                                                return partial_arg(subscription, param);
                                              });
                                          }));
                            }));
              }));
}

function subscribe(subscription, handler) {
  subscription.on("message", handler);
  return /* () */0;
}

function publish(client, name, data) {
  var data$1 = Buffer$LidcoreBsNode.from(/* None */0, data);
  return BsAsyncMonad.Callback[/* >> */5](get_topic(client, name), (function (topic) {
                var publisher = topic.publisher();
                return (function (param) {
                    publisher.publish(data$1, param);
                    return /* () */0;
                  });
              }));
}

function publishBatch(projectId, topic, messages) {
  var client = new (Pubsub.v1.PublisherClient)();
  var topic$1 = client.topicPath(projectId, topic);
  var messages$1 = $$Array.map((function (msg) {
          return {
                  data: Buffer$LidcoreBsNode.from(/* None */0, msg)
                };
        }), messages);
  var request = {
    topic: topic$1,
    messages: messages$1
  };
  return (function (param) {
      client.publish(request, param);
      return /* () */0;
    });
}

function init$1($staropt$star, _) {
  var config = $staropt$star ? $staropt$star[0] : default_config;
  var gcs = Storage(config);
  var request = function (ops) {
    ops.forever = false;
    return ops;
  };
  var interceptor = {
    request: request
  };
  gcs.interceptors.push(interceptor);
  return gcs;
}

function getSignedUrl(config, file, cb) {
  file.getSignedUrl(config, cb);
  return /* () */0;
}

function init$2($staropt$star, _) {
  return new Firestore($staropt$star ? $staropt$star[0] : default_config);
}

var Not_saved = Caml_exceptions.create("Gcloud-LidcoreDraco.Firestore.Document.Not_saved");

function is_saved(param) {
  return param[1] !== /* None */0;
}

function saved(doc) {
  if (doc[1] === /* None */0) {
    throw Not_saved;
  }
  return doc;
}

function process_snapshot(ref, snapshot) {
  if (snapshot.exists) {
    var partial_arg_001 = /* Some */[snapshot.data()];
    var partial_arg = /* tuple */[
      ref,
      partial_arg_001
    ];
    var partial_arg$1 = BsAsyncMonad.Callback[/* return */2];
    return (function (param) {
        return partial_arg$1(partial_arg, param);
      });
  } else {
    var partial_arg$2 = /* tuple */[
      ref,
      /* None */0
    ];
    var partial_arg$3 = BsAsyncMonad.Callback[/* return */2];
    return (function (param) {
        return partial_arg$3(partial_arg$2, param);
      });
  }
}

function save(param, data) {
  var ref = param[0];
  data.timestamp = Date$LidcoreDraco.now(/* () */0);
  var partial_arg = param[1] === /* None */0 ? ref.create(data) : ref.update(data);
  var partial_arg$1 = BsAsyncMonad.Callback[/* from_promise */0];
  return BsAsyncMonad.Callback[/* >> */5]((function (param) {
                return partial_arg$1(partial_arg, param);
              }), (function () {
                var partial_arg_001 = /* Some */[data];
                var partial_arg = /* tuple */[
                  ref,
                  partial_arg_001
                ];
                var partial_arg$1 = BsAsyncMonad.Callback[/* return */2];
                return (function (param) {
                    return partial_arg$1(partial_arg, param);
                  });
              }));
}

function get(param, key) {
  var data = param[1];
  if (data) {
    return Js_null_undefined.fromOption(Js_primitive.undefined_to_opt(data[0][key]));
  } else {
    return null;
  }
}

function path(param) {
  return param[0].path;
}

function $$delete(param) {
  var ref = param[0];
  var partial_arg = ref.delete();
  var partial_arg$1 = BsAsyncMonad.Callback[/* from_promise */0];
  return BsAsyncMonad.Callback[/* >| */9]((function (param) {
                return partial_arg$1(partial_arg, param);
              }), (function () {
                return /* tuple */[
                        ref,
                        /* None */0
                      ];
              }));
}

function $$document(firestore, name) {
  var ref = firestore.doc(name);
  var partial_arg = ref.get();
  var partial_arg$1 = BsAsyncMonad.Callback[/* from_promise */0];
  return BsAsyncMonad.Callback[/* >> */5]((function (param) {
                return partial_arg$1(partial_arg, param);
              }), (function (param) {
                return process_snapshot(ref, param);
              }));
}

function docs(q) {
  return $$Array.map((function (d) {
                return /* tuple */[
                        d.ref,
                        /* Some */[d.data()]
                      ];
              }), q.docs);
}

var QuerySnapshot = /* module */[/* docs */docs];

function get$1(c) {
  var partial_arg = c.get();
  var partial_arg$1 = BsAsyncMonad.Callback[/* from_promise */0];
  return (function (param) {
      return partial_arg$1(partial_arg, param);
    });
}

function collections(db) {
  var partial_arg = db.getCollections();
  var partial_arg$1 = BsAsyncMonad.Callback[/* from_promise */0];
  return (function (param) {
      return partial_arg$1(partial_arg, param);
    });
}

function get$2(param, name) {
  var ref = param[1].doc(name);
  var partial_arg = param[0].get(ref);
  var partial_arg$1 = BsAsyncMonad.Callback[/* from_promise */0];
  return BsAsyncMonad.Callback[/* >> */5]((function (param) {
                return partial_arg$1(partial_arg, param);
              }), (function (param) {
                return process_snapshot(ref, param);
              }));
}

function write(tr) {
  return tr;
}

function save$1(param, param$1, data) {
  var ref = param$1[0];
  var tr = param[0];
  data.timestamp = Date$LidcoreDraco.now(/* () */0);
  if (param$1[1] === /* None */0) {
    tr.create(ref, data);
  } else {
    tr.update(ref, data);
  }
  return /* tuple */[
          ref,
          /* Some */[data]
        ];
}

function $$delete$1(param, param$1) {
  var ref = param$1[0];
  param[0].delete(ref);
  return /* tuple */[
          ref,
          /* None */0
        ];
}

var Transaction = /* module */[
  /* get */get$2,
  /* write */write,
  /* save */save$1,
  /* delete */$$delete$1
];

function runTransaction(options, firestore, fn) {
  var options$1 = Js_null_undefined.fromOption(options);
  var run = function (tr) {
    try {
      return BsAsyncMonad.Callback[/* to_promise */1](Curry._1(fn, /* tuple */[
                      tr,
                      firestore
                    ]));
    }
    catch (raw_exn){
      return Promise.reject(Js_exn.internalToOCamlException(raw_exn));
    }
  };
  var partial_arg = firestore.runTransaction(run, options$1);
  var partial_arg$1 = BsAsyncMonad.Callback[/* from_promise */0];
  return (function (param) {
      return partial_arg$1(partial_arg, param);
    });
}

var options = {
  maxAttempts: 10
};

function incr(param) {
  var path = param[1];
  return runTransaction(/* Some */[options], param[0], (function (tr) {
                return BsAsyncMonad.Callback[/* >> */5](get$2(tr, path), (function (doc) {
                              var match = get(doc, "counter");
                              var v = (match == null) ? 1 : match + 1 | 0;
                              save$1(tr, doc, {
                                    counter: v
                                  });
                              var partial_arg = BsAsyncMonad.Callback[/* return */2];
                              return (function (param) {
                                  return partial_arg(v, param);
                                });
                            }));
              }));
}

function $$delete$2(param) {
  return BsAsyncMonad.Callback[/* >> */5]($$document(param[0], param[1]), (function (doc) {
                return BsAsyncMonad.Callback[/* >| */9]($$delete(doc), (function () {
                              return /* () */0;
                            }));
              }));
}

function counter(firestore, name) {
  return /* tuple */[
          firestore,
          name
        ];
}

function latest_cleanup(db) {
  return BsAsyncMonad.Callback[/* >| */9]($$document(db, "admin/latest_cleanup"), (function (doc) {
                try {
                  var doc$1 = saved(doc);
                  return /* Some */[get(doc$1, "timestamp")];
                }
                catch (exn){
                  if (exn === Not_saved) {
                    return /* None */0;
                  } else {
                    throw exn;
                  }
                }
              }));
}

var cleanup_after = 5 * 24 * 60 * 60 * 1000;

function cleanup_collection(db, c) {
  var now = Date$LidcoreDraco.now(/* () */0);
  var cleanup = function (docs) {
    return runTransaction(/* None */0, db, (function (tr) {
                  $$Array.iter((function (doc) {
                          $$delete$1(tr, doc);
                          return /* () */0;
                        }), docs);
                  var partial_arg = BsAsyncMonad.Callback[/* return */2];
                  return (function (param) {
                      return partial_arg(/* () */0, param);
                    });
                }));
  };
  var c$1 = c.where("timestamp", "<=", now - cleanup_after);
  var partial_arg = c$1.get();
  var partial_arg$1 = BsAsyncMonad.Callback[/* from_promise */0];
  return BsAsyncMonad.Callback[/* >> */5]((function (param) {
                return partial_arg$1(partial_arg, param);
              }), (function (query) {
                var docs$1 = docs(query);
                var partial_arg = Utils$LidcoreDraco.partition(500, docs$1);
                var partial_arg$1 = BsAsyncMonad.Callback[/* itera */17];
                return (function (param) {
                    return partial_arg$1(/* None */0, cleanup, partial_arg, param);
                  });
              }));
}

function init$3($staropt$star, _) {
  return new Compute($staropt$star ? $staropt$star[0] : default_config);
}

function PubSub_004(prim) {
  prim.ack();
  return /* () */0;
}

function PubSub_005(prim) {
  prim.nack();
  return /* () */0;
}

var PubSub = [
  init,
  publish,
  publishBatch,
  subscription,
  PubSub_004,
  PubSub_005,
  subscribe
];

function Storage_001(prim, prim$1) {
  return prim.bucket(prim$1);
}

function Storage_002(prim, prim$1) {
  return prim.file(prim$1);
}

function Storage_003(prim) {
  return prim.createReadStream();
}

function Storage_004(prim) {
  return prim.createWriteStream();
}

var Storage$1 = [
  init$1,
  Storage_001,
  Storage_002,
  Storage_003,
  Storage_004,
  getSignedUrl
];

var Firestore_001 = [
  Not_saved,
  is_saved,
  saved,
  save,
  get,
  path,
  $$delete
];

var Firestore_004 = [
  (function (prim) {
      return prim.id;
    }),
  get$1
];

function Firestore_005(prim, prim$1) {
  return prim.collection(prim$1);
}

var Firestore_009 = [
  incr,
  $$delete$2
];

var Firestore$1 = [
  init$2,
  Firestore_001,
  $$document,
  QuerySnapshot,
  Firestore_004,
  Firestore_005,
  collections,
  Transaction,
  runTransaction,
  Firestore_009,
  counter,
  latest_cleanup,
  cleanup_collection
];

var Compute_001 = [(function (prim, prim$1) {
      prim.getMetadata(prim$1);
      return /* () */0;
    })];

var Compute_002 = [(function (prim, prim$1) {
      return prim.vm(prim$1);
    })];

function Compute_003(prim, prim$1) {
  return prim.zone(prim$1);
}

var Compute$1 = [
  init$3,
  Compute_001,
  Compute_002,
  Compute_003
];

exports.project = project;
exports.PubSub = PubSub;
exports.Storage = Storage$1;
exports.Firestore = Firestore$1;
exports.Compute = Compute$1;
/* project Not a pure module */
