// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Requireall = require("requireall");

function exec(prim) {
  Requireall(prim);
  return /* () */0;
}

exports.exec = exec;
/* requireall Not a pure module */
