// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Shell = require("shell");

function cp($staropt$star, src, dst) {
  var options = $staropt$star ? $staropt$star[0] : "";
  Shell.cp(options, src, dst);
  return /* () */0;
}

exports.cp = cp;
/* shell Not a pure module */
