// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Shelljs = require("shelljs");

function cp($staropt$star, src, dst) {
  var options = $staropt$star ? $staropt$star[0] : "";
  Shelljs.cp(options, src, dst);
  return /* () */0;
}

exports.cp = cp;
/* shelljs Not a pure module */
