// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var NodeYaml = require("node-yaml");

function parse(prim) {
  return NodeYaml.parse(prim);
}

exports.parse = parse;
/* node-yaml Not a pure module */
